// <auto-generated />
using System;
using BookingApp.Repository.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingApp.Repository.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20220803033102_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("BookingApp.Entities.POCOs.Recurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("RecursoId");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("BookingApp.Entities.POCOs.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReservaId");

                    b.Property<DateTime>("FechaFinReserva")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicioReserva")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreReserva")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SalaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BookingApp.Entities.POCOs.Sala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SalaId");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("BookingApp.Entities.POCOs.Recurso", b =>
                {
                    b.HasOne("BookingApp.Entities.POCOs.Reserva", null)
                        .WithMany("Recursos")
                        .HasForeignKey("ReservaId");
                });

            modelBuilder.Entity("BookingApp.Entities.POCOs.Reserva", b =>
                {
                    b.HasOne("BookingApp.Entities.POCOs.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("BookingApp.Entities.POCOs.Reserva", b =>
                {
                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
